- hosts: localhost
  connection: local
  become: true
  vars:
    local_user: tiago
    apt_packages:
      - htop
      - python3-pip
      - python3-venv
      - zsh
      - git
      - curl
      - solaar
      - tilix
      - gnome-tweaks
    snap_packages:
      - code
      - gitkraken
    oh_my_zsh_repos:
      - repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
      - repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    zsh_config:
      - url: https://raw.githubusercontent.com/JamesHaughey/linux_installs/master/dotfiles/.zshrc
        dest: ~/.zshrc
      - url: https://raw.githubusercontent.com/JamesHaughey/linux_installs/master/dotfiles/.p10k.zsh
        dest: ~/.p10k.zsh
    fonts:
      - MesloLGS%20NF%20Regular.ttf
      - MesloLGS%20NF%20Bold.ttf
      - MesloLGS%20NF%20Italic.ttf
      - MesloLGS%20NF%20Bold%20Italic.ttf
    vs_code_extensions:
      - ms-python.python
      - mhutchie.git-graph
      - eamodio.gitlens
      - codezombiech.gitignore
      - esbenp.prettier-vscode
      - hackmd.vscode-hackmd
      - yzhang.markdown-all-in-one
      - redhat.vscode-yaml
      - ms-vscode-remote.vscode-remote-extensionpack
      - dahong.theme-bear
      - pkief.material-icon-theme
      - mechatroner.rainbow-csv
      - oderwat.indent-rainbow
      - 2gua.rainbow-brackets

  tasks:
    - name: Install apt packages
      apt:
        name: "{{ apt_packages }}"

    - name: Install snap packages
      community.general.snap:
        name: "{{ snap_packages }}"
        classic: yes

    - name: Install VS Code Extensions
      become: yes
      become_user: "{{ local_user }}"
      command: "code --install-extension {{ item }}"
      loop: "{{ vs_code_extensions }}"

    - name: Download oh-my-zsh install script
      become: yes
      become_user: "{{ local_user }}"
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: ~/Downloads/0h-my-zsh-installer.sh
        mode: u+rwx
      notify: Execute oh-my-zsh install script

    - name: Clone oh-my-zsh repos
      become: yes
      become_user: "{{ local_user }}"
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop: "{{ oh_my_zsh_repos }}"

    - name: Download zsh config files
      become: yes
      become_user: "{{ local_user }}"
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      loop: "{{ zsh_config }}"

    - name: Create fonts folder
      become: yes
      become_user: "{{ local_user }}"
      file:
        path: ~/.fonts/
        state: directory
        mode: "0755"

    - name: Download Fonts
      become: yes
      become_user: "{{ local_user }}"
      get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item }}"
        dest: "~/.fonts/{{ item }}"
      loop: "{{ fonts }}"

    - name: Set local_user shell to zsh
      user:
        name: "{{ local_user }}"
        shell: /bin/zsh

  handlers:
    - name: Execute oh-my-zsh install script
      shell: ~/Downloads/0h-my-zsh-installer.sh
      become: yes
      become_user: "{{ local_user }}"

  

