- hosts: localhost
  connection: local
  become: true
  vars:
    local_user: tiago
    apt_packages:
      - htop
      - python3-pip
      - python3-venv
      - zsh
      - git
      - curl
      - solaar
      - tilix
      - gnome-tweaks
    snap_packages:
      - code
      - gitkraken
    oh_my_zsh_repos:
      - repo: https://github.com/romkatv/powerlevel10k.git
        dest: ~/.oh-my-zsh/custom/themes/powerlevel10k
      - repo: https://github.com/zsh-users/zsh-autosuggestions
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    zsh_config:
      - url: https://raw.githubusercontent.com/JamesHaughey/linux_installs/master/dotfiles/.zshrc
        dest: ~/.zshrc
      - url: https://raw.githubusercontent.com/JamesHaughey/linux_installs/master/dotfiles/.p10k.zsh
        dest: ~/.p10k.zsh

  tasks:
    - name: Install apt packages
      apt:
        name: "{{ apt_packages }}"

    - name: Install snap packages
      community.general.snap:
        name: "{{ snap_packages }}"
        classic: yes

    - name: Download oh-my-zsh install script
      become: yes
      become_user: "{{ local_user }}"
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: ~/Downloads/0h-my-zsh-installer.sh
        mode: u+rwx
      notify: Execute oh-my-zsh install script

    - name: Clone oh-my-zsh repos
      become: yes
      become_user: "{{ local_user }}"
      git:
        repo: "{{ item.repo }}"
        dest: "{{ item.dest }}"
      loop: "{{ oh_my_zsh_repos }}"

    - name: Download zsh config files
      become: yes
      become_user: "{{ local_user }}"
      get_url:
        url: "{{ item.url }}"
        dest: "{{ item.dest }}"
      loop: "{{ zsh_config }}"

    - name: Set local_user shell to zsh
      user:
        name: "{{ local_user }}"
        shell: /bin/zsh

  handlers:
    - name: Execute oh-my-zsh install script
      shell: ~/Downloads/0h-my-zsh-installer.sh
      become: yes
      become_user: "{{ local_user }}"

  

