- hosts: localhost
  connection: local
  become: true
  vars:
    apt_packages:
      - htop
      - python3-pip
      - python3-venv
      - zsh
      - git
      - curl
      - solaar
      - tilix
      - gnome-tweaks
    snap_packages:
      - code
      - gitkraken

  tasks:
  - name: Install apt packages
    apt:
      name: "{{ apt_packages }}"
  - name: Install snap packages
    community.general.snap:
      name: "{{ snap_packages }}"
      classic: yes


  # - name: Download install script
  #   get_url:
  #     url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  #     dest: ~/Downloads/0h-my-zsh-installer.sh
  #     mode: u+rwx

  # - name: Execute install script
  #   shell: ~/Downloads/0h-my-zsh-installer.sh
  # - name: Remove the install script
  #   file:
  #     path: ~/Downloads/0h-my-zsh-installer.sh
  #     state: absent
  # handlers:

